version: '3'


services:

  postgres:
    image: postgres:latest
    network_mode: "bridge"
    volumes:
      - "/docker/ficelle/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=ficelle
      - POSTGRES_USER=ficelle

  redis:
    image: redis:latest
    network_mode: "bridge"
    volumes:
      - "/docker/ficelle/redis:/data"

  migrate:
    image: blusky/ficelle:latest
    network_mode: "bridge"
    command: python manage.py migrate
    depends_on:
      - postgres
      - redis

  web:
    image: blusky/ficelle:latest
    network_mode: "bridge"
    command: daphne -b 0.0.0.0 ficelle.asgi:channel_layer
    links:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - FICELLE_DEBUG=False
      - FICELLE_ALLOW_REGISTER=False
    depends_on:
      - postgres
      - redis
      - migrate
      - celery_beat
      - celery_worker
      - web_worker

  web_worker:
    image: blusky/ficelle:latest
    network_mode: "bridge"
    links:
      - postgres
      - redis
    command: python manage.py runworker
    depends_on:
      - postgres
      - redis

  celery_beat:
    image: blusky/ficelle:latest
    network_mode: "bridge"
    links:
      - postgres
      - redis
    command: python celery_beat.py
    depends_on:
      - postgres
      - redis

  celery_worker:
    image: blusky/ficelle:latest
    network_mode: "bridge"
    links:
      - postgres
      - redis
    command: python celery_worker.py
    depends_on:
      - celery_beat
      - postgres
      - redis
